import React, {useState} from "react";
import {FontAwesomeIcon} from "@fortawesome/react-fontawesome";
import {faCirclePlus} from "@fortawesome/free-solid-svg-icons";
import axios from "axios";
import {toast} from "react-toastify";

export default function CreateUser({onUserCreated}) {
  // State to manage the modal visibility
  const [showModal, setShowModal] = useState(false);

  // Form fields for creating a user
  const [username, setUsername] = useState("");
  const [phoneNumber, setPhoneNumber] = useState("");
  const [email, setEmail] = useState("");
  const [address, setAddress] = useState("");
  const [role, setRole] = useState("");
  const [password, setPassword] = useState("");
  const [ratings, setRatings] = useState("");
  const [status, setStatus] = useState(0); // Default status to "Accept" (0)
  const [errors, setErrors] = useState([]);

  // Functions to open and close the modal
  const handleShow = () => setShowModal(true);
  const handleClose = () => {
    setShowModal(false);
    setErrors([]);
    setUsername("");
    setPhoneNumber("");
    setEmail("");
    setAddress("");
    setRole("");
    setPassword("");
    setRatings("");
    setStatus(0);
  };

  const handleSubmit = (e) => {
    e.preventDefault();

    const userData = {
      userId: "", // Leave userId empty as it will be autogenerated by the backend
      username,
      phoneNumber: parseInt(phoneNumber),
      email,
      address,
      role,
      password,
      ratings,
      status,
    };

    // Reset errors
    setErrors([]);

    // Post the data to the API to create the user
    axios
      .post(`${process.env.REACT_APP_WEB_API}/Users`, userData)
      .then((response) => {
        // Handle success
        console.log("User created successfully:", response.data);
        toast.success("User created successfully!");
        window.location.reload();

        // Close the modal and reset the form
        handleClose();

        // Notify parent component to refresh the user list if applicable
        if (onUserCreated) {
          onUserCreated(response.data.user);
        }
      })
      .catch((error) => {
        // Handle error
        console.error("There was an error creating the user!", error);
        if (error.response && error.response.data) {
          const responseData = error.response.data;
          if (responseData.errors) {
            const errorMessages = [];
            for (const key in responseData.errors) {
              errorMessages.push(...responseData.errors[key]);
            }
            setErrors(errorMessages);
            errorMessages.forEach((err) => toast.error(err));
          } else if (responseData.message) {
            setErrors([responseData.message]);
            toast.error(responseData.message);
          } else {
            setErrors(["An unexpected error occurred."]);
            toast.error("An unexpected error occurred.");
          }
        } else {
          setErrors(["An unexpected error occurred."]);
          toast.error("An unexpected error occurred.");
        }
      });
  };

  return (
    <>
      {/* Button to trigger the modal */}
      <button
        type="button"
        className="btn btn-success d-flex align-items-center"
        onClick={handleShow}
      >
        <FontAwesomeIcon icon={faCirclePlus} className="me-2" /> Create User
      </button>

      {/* Modal */}
      {showModal && (
        <div
          className="modal fade show"
          tabIndex="-1"
          role="dialog"
          style={{display: "block", backgroundColor: "rgba(0, 0, 0, 0.5)"}}
        >
          <div className="modal-dialog modal-lg d-flex justify-content-center">
            <div className="modal-content">
              <div className="modal-header">
                <h5 className="modal-title">Create New User</h5>
                <button
                  type="button"
                  className="btn-close"
                  onClick={handleClose}
                  aria-label="Close"
                ></button>
              </div>

              {/* Full modal body without scrolling */}
              <div className="modal-body p-4">
                {errors.length > 0 && (
                  <div className="alert alert-danger">
                    <ul>
                      {errors.map((error, index) => (
                        <li key={index}>{error}</li>
                      ))}
                    </ul>
                  </div>
                )}
                <form onSubmit={handleSubmit}>
                  <div className="row">
                    {/* Left Column */}
                    <div className="col-md-6">
                      {/* Username input */}
                      <div className="form-outline mb-4">
                        <label className="form-label" htmlFor="username">
                          Username
                        </label>
                        <input
                          type="text"
                          id="username"
                          className="form-control"
                          placeholder="Enter username"
                          value={username}
                          onChange={(e) => setUsername(e.target.value)}
                          required
                        />
                      </div>

                      {/* Phone Number input */}
                      <div className="form-outline mb-4">
                        <label className="form-label" htmlFor="phoneNumber">
                          Phone Number
                        </label>
                        <input
                          type="number"
                          id="phoneNumber"
                          className="form-control"
                          placeholder="Enter phone number"
                          value={phoneNumber}
                          onChange={(e) => setPhoneNumber(e.target.value)}
                          required
                        />
                      </div>

                      {/* Email input */}
                      <div className="form-outline mb-4">
                        <label className="form-label" htmlFor="email">
                          Email
                        </label>
                        <input
                          type="email"
                          id="email"
                          className="form-control"
                          placeholder="Enter email"
                          value={email}
                          onChange={(e) => setEmail(e.target.value)}
                          required
                        />
                      </div>
                    </div>

                    {/* Right Column */}
                    <div className="col-md-6">
                      {/* Address input */}
                      <div className="form-outline mb-4">
                        <label className="form-label" htmlFor="address">
                          Address
                        </label>
                        <input
                          type="text"
                          id="address"
                          className="form-control"
                          placeholder="Enter address"
                          value={address}
                          onChange={(e) => setAddress(e.target.value)}
                          required
                        />
                      </div>

                      {/* Role input */}
                      <div className="form-outline mb-4">
                        <label className="form-label" htmlFor="role">
                          Role
                        </label>
                        <select
                          id="role"
                          className="form-control"
                          value={role}
                          onChange={(e) => setRole(e.target.value)}
                        >
                          <option value={"Admin"}>Admin</option>
                          <option value={"CRS"}>CRS</option>
                          <option value={"Vendor"}>Vendor</option>
                          <option value={"Customer"}>Customer</option>
                        </select>
                      </div>

                      {/* Password input */}
                      <div className="form-outline mb-4">
                        <label className="form-label" htmlFor="password">
                          Password
                        </label>
                        <input
                          type="password"
                          id="password"
                          className="form-control"
                          placeholder="Enter password"
                          value={password}
                          onChange={(e) => setPassword(e.target.value)}
                          required
                        />
                      </div>

                      {/* Ratings input */}
                      <div className="form-outline mb-4">
                        <label className="form-label" htmlFor="ratings">
                          Ratings (optional)
                        </label>
                        <input
                          type="text"
                          id="ratings"
                          className="form-control"
                          placeholder="Enter ratings"
                          value={ratings}
                          onChange={(e) => setRatings(e.target.value)}
                        />
                      </div>

                      {/* Status input */}
                      <div className="form-outline mb-4">
                        <label className="form-label" htmlFor="status">
                          Status
                        </label>
                        <select
                          id="status"
                          className="form-control"
                          value={status}
                          onChange={(e) => setStatus(parseInt(e.target.value))}
                        >
                          <option value={0}>Accept</option>
                          <option value={1}>Reject</option>
                          <option value={2}>Hold</option>
                          <option value={3}>Pending</option>
                        </select>
                      </div>
                    </div>
                  </div>

                  {/* Submit button */}
                  <button type="submit" className="btn btn-primary btn-block">
                    Submit
                  </button>

                  {/* Close button inside the modal body */}
                  <button
                    type="button"
                    className="btn btn-secondary btn-block mt-3"
                    onClick={handleClose}
                  >
                    Close
                  </button>
                </form>
              </div>
            </div>
          </div>
        </div>
      )}
    </>
  );
}
